### ISSUE TITLE
[Question] is main.go the only relevant script?

### ISSUE THREAD

**Issue by simkimsia** [tmc/ent2d2#4]
Hi there, 

i like what you have done.

i am a python dev, i like to do the same except:

- `/r/go/python`
- `/r/ent/django orm`

if main.go is all of it, my plan is to take what you have done in main.go and use chatgpt and help me eventually get to django-models-to-d2

**Comment by tmc** [comment]
Hi! thanks! I think it'd be super cool to do the same for django models and I very much support it! 

Yes. The entirety of this program is defined in main.go.

I wonder, is it sensible to parse django models from go? I'm not sure of the current state of python parsing in go. Might be fun to give it a whirl. Please report back your progress!

I'm going to close this for now but don't hesitate to reach out if you have questions.
